export const DEFAULT_PERMISSIONS: {
  code: string;
  name: string;
  group: string;
  isCustom?: boolean;
}[] = [
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCompanyMemberIdDelete', isCustom: false, name: 'Api Admin Company Company Id Company Member Company Member Id Delete', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCompanyMemberIdRead', isCustom: false, name: 'Api Admin Company Company Id Company Member Company Member Id Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCompanyMemberIdUpdate', isCustom: false, name: 'Api Admin Company Company Id Company Member Company Member Id Update', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCreate', isCustom: false, name: 'Api Admin Company Company Id Company Member Create', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberRead', isCustom: false, name: 'Api Admin Company Company Id Company Member Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesFeatureCodeCreate', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Feature Code Create', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesFeatureCodeDelete', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Feature Code Delete', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesRead', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesUpdate', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Update', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdRead', isCustom: false, name: 'Api Admin Company Company Id Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdRoleRoleNameResetCreate', isCustom: false, name: 'Api Admin Company Company Id Role Role Name Reset Create', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdUpdate', isCustom: false, name: 'Api Admin Company Company Id Update', group: '_admin' },
  { code: 'apiAdminCompanyCreate', isCustom: false, name: 'Api Admin Company Create', group: '_admin' },
  { code: 'apiAdminCompanyRead', isCustom: false, name: 'Api Admin Company Read', group: '_admin' },
  { code: 'apiAdminFeatureFeatureIdDelete', isCustom: false, name: 'Api Admin Feature Feature Id Delete', group: '_admin' },
  { code: 'apiAdminFeatureFeatureIdRead', isCustom: false, name: 'Api Admin Feature Feature Id Read', group: '_admin' },
  { code: 'apiAdminFeatureFeatureIdUpdate', isCustom: false, name: 'Api Admin Feature Feature Id Update', group: '_admin' },
  { code: 'apiAdminFeatureRead', isCustom: false, name: 'Api Admin Feature Read', group: '_admin' },
  { code: 'apiAdminPermissionCreate', isCustom: false, name: 'Api Admin Permission Create', group: '_admin' },
  { code: 'apiAdminPermissionGroupRenameCreate', isCustom: false, name: 'Api Admin Permission Group Rename Create', group: '_admin' },
  { code: 'apiAdminPermissionPermissionIdDelete', isCustom: false, name: 'Api Admin Permission Permission Id Delete', group: '_admin' },
  { code: 'apiAdminPermissionPermissionIdRead', isCustom: false, name: 'Api Admin Permission Permission Id Read', group: '_admin' },
  { code: 'apiAdminPermissionPermissionIdUpdate', isCustom: false, name: 'Api Admin Permission Permission Id Update', group: '_admin' },
  { code: 'apiAdminPermissionRead', isCustom: false, name: 'Api Admin Permission Read', group: '_admin' },
  { code: 'apiAdminUserFilterOptionsRead', isCustom: false, name: 'Api Admin User Filter Options Read', group: '_admin' },
  { code: 'apiAdminUsersRead', isCustom: false, name: 'Api Admin Users Read', group: '_admin' },
  { code: 'apiAdminUsersUserIdRead', isCustom: false, name: 'Api Admin Users User Id Read', group: '_admin' },
  { code: 'apiAdminUsersUserIdRolesUpdate', isCustom: false, name: 'Api Admin Users User Id Roles Update', group: '_admin' },
  { code: 'apiAdminUsersUserIdSessionsDelete', isCustom: false, name: 'Api Admin Users User Id Sessions Delete', group: '_admin' },
  { code: 'apiAdminUsersUserIdSessionsRead', isCustom: false, name: 'Api Admin Users User Id Sessions Read', group: '_admin' },
  { code: 'apiCompanyMemberCompanyIdCompanyMemberIdDelete', isCustom: false, name: 'Api Company Member Company Id Company Member Id Delete', group: 'company-members-manage' },
  { code: 'apiCompanyMemberCompanyIdCompanyMemberIdRead', isCustom: false, name: 'Api Company Member Company Id Company Member Id Read', group: 'user-basics' },
  { code: 'apiCompanyMemberCompanyIdCompanyMemberIdUpdate', isCustom: false, name: 'Api Company Member Company Id Company Member Id Update', group: 'company-members-manage' },
  { code: 'apiCompanyMemberCompanyIdCreate', isCustom: false, name: 'Api Company Member Company Id Create', group: 'company-members-manage' },
  { code: 'apiCompanyMemberCompanyIdRead', isCustom: false, name: 'Api Company Member Company Id Read', group: 'user-basics' },
  { code: 'apiPermissionsRead', isCustom: false, name: 'Api Permissions Read', group: 'user-basics' },
  { code: 'apiUserCurrentRead', isCustom: false, name: 'Api User Current Read', group: 'user-basics' },
  { code: 'apiUserCurrentUpdate', isCustom: false, name: 'Api User Current Update', group: 'user-basics' },
];
